title: New Relic Policy Setup
name: newrelic-stack-setup
description: This is used to configure the New Relic Dynamic Group, Policies, Key Vault and Link to the Newrelic Account.
schemaVersion: 1.1.0
version: 1.0
locale: "en"
groupings:
  - title: "New Relic Environment Configuration"
    variables:
      - ${tenancy_ocid}
      - ${newrelic_ingest_api_key}
      - ${newrelic_user_api_key}
      - ${newrelic_account_id}
  - title: "New Relic Metrics Resource Configuration"
    variables:
      - ${create_metrics_stack}
      - ${dynamic_group_name}
      - ${newrelic_metrics_policy}

variables:
  tenancy_ocid:
    type: string
    title: Tenancy OCID
    description: OCI tenant OCID, more details can be found at https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#five
    required: true
    visible: true

  current_user_ocid:
    type: string
    title: User OCID
    description: The OCID of the current user executing the terraform script.
    required: true
    visible: false

  region:
    type: string
    title: Region
    description: OCI Region as documented at https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm
    required: true
    visible: false

  compartment_ocid:
    type: string
    title: Compartment OCID
    description: The OCID of the compartment where the resources will be created.
    required: true
    visible: false

  dynamic_group_name:
    type: string
    title: New Relic Dynamic Group Name
    description: The name of the dynamic group for giving access to the service connector & Functions
    required: true
    default: newrelic-metrics-dynamic-group
    visible: ${create_metrics_stack}

  newrelic_metrics_policy:
    type: string
    title: New Relic Metrics Policy
    description: The name of the policy for metrics for Function Invocations & Secrets
    required: true
    default: newrelic-metrics-policy
    visible: ${create_metrics_stack}

  newrelic_ingest_api_key:
    type: string
    title: New Relic Ingest API Key
    description: The Ingest API key for sending metrics to New Relic endpoints
    required: true
    sensitive: true
    password: true
    confirmation: true

  newrelic_user_api_key:
    type: string
    title: New Relic User API Key
    description: The User API key for Linking the OCI Account to the New Relic account
    required: true
    sensitive: true
    password: true
    confirmation: true

  newrelic_account_id:
    type: string
    title: New Relic Account ID
    description: The New Relic Account ID for linking the OCI account to the New Relic account
    required: true
    sensitive: true
    confirmation: true

  create_metrics_stack:
    type: boolean
    title: Create Metrics Stack
    description: Whether to create the New Relic metrics stacks(Policies/Dynamic Groups) or not
    required: true
    default: true
