title: New Relic Policy Setup
name: newrelic-stack-setup
description: This is used to configure the New Relic Dynamic Group, Policies, Key Vault and Link to the Newrelic Account.
schemaVersion: 1.1.0
version: 1.0
locale: "en"
groupings:
  - title: "New Relic Environment Configuration"
    variables:
      - ${tenancy_ocid}
      - ${newrelic_ingest_api_key}
      - ${newrelic_user_api_key}
      - ${newrelic_account_id}
      - ${policy_stack}
  - title: "OCI WIF Configuration"
    variables:
      - ${client_id}
      - ${client_secret}
      - ${oci_domain_url}
      - ${svc_user_name}

variables:
  tenancy_ocid:
    type: string
    title: Tenancy OCID
    description: OCI tenant OCID, more details can be found at https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#five
    required: true
    visible: true

  current_user_ocid:
    type: string
    title: User OCID
    description: The OCID of the current user executing the terraform script.
    required: true
    visible: false

  region:
    type: string
    title: Region
    description: OCI Region as documented at https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm
    required: true
    visible: false

  compartment_ocid:
    type: string
    title: Compartment OCID
    description: The OCID of the compartment where the resources will be created.
    required: true
    visible: false

  newrelic_ingest_api_key:
    type: string
    title: New Relic Ingest - Licence API Key
    description: The Ingest Licence API key for sending metrics to New Relic endpoints
    required: true
    sensitive: true
    password: true
    confirmation: true

  newrelic_user_api_key:
    type: string
    title: New Relic User API Key
    description: The User API key for Linking the OCI Account to the New Relic account
    required: true
    sensitive: true
    password: true
    confirmation: true

  newrelic_account_id:
    type: string
    title: New Relic Account ID
    description: The New Relic Account ID for linking the OCI account to the New Relic account
    required: true
    sensitive: true
    confirmation: true

  policy_stack:
    type: string
    title: New Relic Policy Instrumentation
    description: A string indicating which parts of the stack to deploy. Use comma-separated values from METRICS, LOGS, COMMON.
    visible: true
    required: true

  client_id:
    type: string
    title: Client ID
    description: The Client ID for OCI tenancy, needed for metadata polling from New Relic.
    required: true
    visible: true

  client_secret:
    type: string
    title: Client Secret
    description: The Client Secret for the OCI tenancy, needed for metadata polling from New Relic.
    required: true
    sensitive: true
    password: true
    confirmation: true

  oci_domain_url:
    type: string
    title: OCI Domain URL
    description: The OCI Domain URL, usually https://identity.<region>.oraclecloud.com
    required: true
    visible: true

  svc_user_name:
    type: string
    title: Service User Name
    description: The name of the service user created in OCI for New Relic to access the tenancy.
    required: true
    visible: true


