title: New Relic Configuration for Sending Metrics
name: newrelic-stack-setup
description: This is used to configure the New Relic setup for sending metrics from various OCI services.
schemaVersion: 1.1.0
version: 1.0
locale: "en"
variableGroups:
  - title: "New Relic Environment Configuration"
    variables:
      - ${newrelic_endpoint}
      - ${newrelic_account_id}
      - ${nr_prefix}
      - ${payload_link}
  - title: "Network options"
    variables:
      - ${create_vcn}
      - ${vcnCompartment}
      - ${existingVcn}
      - ${function_subnet_id}

variables:
  tenancy_ocid:
    type: string
    title: Tenancy OCID
    description: OCI tenant OCID, more details can be found at https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#five
    required: true
    visible: false

  compartment_ocid:
    type: string
    title: Compartment OCID
    description: The OCID of the compartment where the resources will be created.
    required: true
    visible: false

  region:
    type: string
    title: Region
    description: OCI Region as documented at https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm
    required: true
    visible: false

  nr_prefix:
    type: string
    title: New Relic prefix
    description: The prefix to use for New Relic resources for Function and VCNs.
    required: true
    default: metrics

  newrelic_endpoint:
    type: enum
    title: New Relic Endpoint
    description: The endpoint to hit for sending the metrics. Varies by region [Staging|US|EU]
    required: true
    allowMultiple: false
    default: newrelic-metric-api
    enum:
      - newrelic-metric-api
      - newrelic-eu-metric-api

  newrelic_account_id:
    type: string
    title: New Relic Account ID
    description: The New Relic Account ID for linking the OCI account to the New Relic account
    required: true
    sensitive: false
    confirmation: true

  create_vcn:
    title: Create VCN
    description: Create virtual network (VCN) for the function setup. If using existing networking resources, de-select "Create VCN" and select the relevant VCN and subnet to use.
    type: boolean
    default: true

  payload_link:
    title: Payload Link
    description: The link to the payload for the connector hubs.
    type: string
    required: true
    visible: true

  vcnCompartment:
    type: oci:identity:compartment:id
    visible:
      not:
        - ${create_vcn}
  existingVcn:
    type: oci:core:vcn:id
    visible:
      not:
        - ${create_vcn}
    dependsOn:
      compartmentId: ${vcnCompartment}
  function_subnet_id:
    title: Function Subnet OCID
    type: oci:core:subnet:id
    visible:
      not:
        - ${create_vcn}
    description: The subnet to be used by the function app that will be deployed. If "Create VCN" is selected, the new VCN will overwrite this selection..
    required: false
    dependsOn:
      compartmentId: ${vcnCompartment}
      vcnId: ${existingVcn}
