name: Build and Deploy OCI Image

on:
  push:
    branches:
      - main
    paths:
      - 'newrelic-metrics-function/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'newrelic-metrics-function/**'

jobs:
  # Job 1: Build Docker Image on PR Raise
  build_docker_image:
    runs-on: ubuntu-latest
    environment:
      name: build-test-env
    steps:
      - name: Build Only FUNCTION_BUILD_VERSION
        run: |
          major=1
          echo "FUNCTION_BUILD_VERSION=${major}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set permissions for build script
        run: chmod +x script/build_and_push.sh

      - name: Build Docker Image
        run: ./script/build_and_push.sh build-only ${{ env.DEFAULT_BUILD_REGION }}
        env:
          DEFAULT_BUILD_REGION: us-ashburn-1
          ORACLE_AUTH_TOKEN: ${{ secrets.ORACLE_AUTH_TOKEN }}
          OCI_TENANCY_NAMESPACE: ${{ secrets.OCI_TENANCY_NAMESPACE }}
          OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
          FUNCTION_BUILD_VERSION: ${{ env.FUNCTION_BUILD_VERSION }}

  # Job 2: Push Docker Image on PR Merge
  push_docker_image:
    runs-on: ubuntu-latest
    needs: build_docker_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        region:
          - us-ashburn-1
          - us-phoenix-1
          - ap-batam-1
          - ap-sydney-1
          - ap-melbourne-1
          - sa-saopaulo-1
          - sa-vinhedo-1
          - ca-montreal-1
          - ca-toronto-1
          - sa-santiago-1
          - sa-valparaiso-1
          - sa-bogota-1
          - eu-paris-1
          - eu-marseille-1
          - eu-frankfurt-1
          - ap-hyderabad-1
          - ap-mumbai-1
          - il-jerusalem-1
          - eu-milan-1
          - ap-osaka-1
          - ap-tokyo-1
          - mx-queretaro-1
          - mx-monterrey-1
          - eu-amsterdam-1
          - me-riyadh-1
          - me-jeddah-1
          - ap-singapore-1
          - ap-singapore-2
          - af-johannesburg-1
          - ap-seoul-1
          - ap-chuncheon-1
          - eu-madrid-1
          - eu-stockholm-1
          - eu-zurich-1
          - me-abudhabi-1
          - me-dubai-1
          - uk-london-1
          - uk-cardiff-1
          - us-chicago-1
          - us-sanjose-1

    steps:
      - name: Set FUNCTION_BUILD_VERSION
        run: |
          major=1
          minor=$((1 + ${{ github.run_number }}))
          echo "FUNCTION_BUILD_VERSION=${major}.${minor}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set permissions for build script
        run: chmod +x script/build_and_push.sh

      - name: Push Docker Image to ${{ matrix.region }}
        run: ./script/build_and_push.sh full ${{ matrix.region }}
        env:
          ORACLE_AUTH_TOKEN: ${{ secrets.ORACLE_AUTH_TOKEN }}
          OCI_REGION: ${{ matrix.region }}
          OCI_TENANCY_NAMESPACE: ${{ secrets.OCI_TENANCY_NAMESPACE }}
          OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
          FUNCTION_BUILD_VERSION: ${{ env.FUNCTION_BUILD_VERSION }}
